# -*- coding: utf-8 -*-
"""Untitled1.ipyn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lif_glHLjQM_iL8dydIoiD2eOKxQYdeq
"""

import matplotlib.pyplot as plt
from wordcloud import WordCloud

# Define a list of colors for the plots (can still use this)
colors = [
    'skyblue', 'lightcoral', 'lightgreen', 'gold', 'plum',
    'orange', 'lightblue', 'pink', 'lavender', 'salmon'
]

# --- Replace the placeholder data below with your actual data ---

# Data for Top 10 In-Demand Skills (list of tuples: [(skill, count), ...])
top_skills_data = [('Skill A', 100), ('Skill B', 90), ('Skill C', 80), ('Skill D', 70), ('Skill E', 60), ('Skill F', 50), ('Skill G', 40), ('Skill H', 30), ('Skill I', 20), ('Skill J', 10)]

# Data for Skill Clusters Distribution (dictionary: {cluster_name: count, ...})
skill_clusters_data = {'Cluster 1': 50, 'Cluster 2': 30, 'Cluster 3': 20}

# Data for Salary Distribution (dictionary: {'average': avg_salary, '25th %ile': p25_salary, 'median': median_salary, '75th %ile': p75_salary})
salary_stats_data = {'average': 80000, 'percentile_25': 60000, 'median': 75000, 'percentile_75': 95000}

# Data for Job Locations (list of tuples: [(location, count), ...])
locations_data = [('Location X', 40), ('Location Y', 30), ('Location Z', 20)]

# Data for Experience Level Distribution (dictionary: {experience_level: count, ...})
experience_data = {'Entry-Level': 50, 'Mid-Level': 70, 'Senior-Level': 30}

# Data for Top Companies Hiring (list of tuples: [(company, count), ...])
companies_data = [('Company 1', 60), ('Company 2', 50), ('Company 3', 40), ('Company 4', 30), ('Company 5', 20)]

# Data for Market Trends (dictionary: {'recent_postings': count, 'growth_rate': rate, 'salary_trend': 'increasing' or 'decreasing'})
market_trends_data = {'recent_postings': 200, 'growth_rate': 0.05, 'salary_trend': 'increasing'}

# Data for Top Skill Gaps to Address (list of strings: [skill_gap1, skill_gap2, ...])
skill_gaps_data = ['Skill Gap 1', 'Skill Gap 2', 'Skill Gap 3']

# Data for Learning Path Timeline (list of dictionaries: [{'step': 1, 'duration_weeks': 4}, ...])
learning_path_data = [{'step': 1, 'duration_weeks': 4}, {'step': 2, 'duration_weeks': 6}, {'step': 3, 'duration_weeks': 8}]

# Data for Career Progression Path (list of dictionaries: [{'step': 1}, {'step': 2}, ...])
career_progression_data = [{'step': 1}, {'step': 2}, {'step': 3}, {'step': 4}]

# Data for Job Type Distribution (dictionary: {job_type: count, ...})
job_types_data = {'Full-time': 80, 'Part-time': 10, 'Contract': 10}

# Data for Skills Word Cloud (dictionary: {skill: frequency, ...})
skill_distribution_data = {'Python': 50, 'SQL': 40, 'Azure': 30, 'Machine Learning': 35, 'Data Analysis': 45, 'Communication': 25}


# --- Generate the plots ---

print("Generating plots...")

# Plot 1: Top 10 In-Demand Skills
plt.figure(figsize=(10, 6))
skills, counts = zip(*top_skills_data)
plt.barh(skills, counts, color=colors[0])
plt.xlabel('Job Count')
plt.title('Top 10 In-Demand Skills')
plt.gca().invert_yaxis()
plt.show()

# Plot 2: Skill Clusters Distribution
plt.figure(figsize=(8, 8))
skill_clusters_data = {k: v for k, v in skill_clusters_data.items() if v > 0}
plt.pie(skill_clusters_data.values(), labels=skill_clusters_data.keys(), autopct='%1.1f%%')
plt.title('Skill Clusters Distribution')
plt.show()

# Plot 3: Salary Distribution
plt.figure(figsize=(10, 6))
metrics = ['Average', '25th %ile', 'Median', '75th %ile']
values = [salary_stats_data['average'], salary_stats_data['percentile_25'],
         salary_stats_data['median'], salary_stats_data['percentile_75']]
plt.bar(metrics, values, color=colors[2])
plt.title('Salary Distribution')
plt.ylabel('Salary ($)')
plt.xticks(rotation=45)
plt.show()

# Plot 4: Job Locations
plt.figure(figsize=(8, 8))
locations, counts = zip(*locations_data)
plt.pie(counts, labels=locations, autopct='%1.1f%%')
plt.title('Job Locations')
plt.show()

# Plot 5: Experience Level Distribution
plt.figure(figsize=(10, 6))
plt.bar(experience_data.keys(), experience_data.values(), color=colors[4])
plt.title('Experience Level Distribution')
plt.xticks(rotation=45)
plt.show()

# Plot 6: Top Companies Hiring
plt.figure(figsize=(10, 6))
companies, counts = zip(*companies_data)
plt.barh(companies, counts, color=colors[5])
plt.xlabel('Job Count')
plt.title('Top Companies Hiring')
plt.gca().invert_yaxis()
plt.show()

# Plot 7: Market Trends
plt.figure(figsize=(10, 6))
metrics = ['Recent Postings', 'Growth Rate', 'Market Trend']
values = [market_trends_data['recent_postings'], market_trends_data['growth_rate'] * 100,
         1 if market_trends_data['salary_trend'] == 'increasing' else 0.5]
plt.bar(metrics, values, color=colors[6])
plt.title('Market Trends')
plt.show()

# Plot 8: Top Skill Gaps to Address
plt.figure(figsize=(10, 6))
if skill_gaps_data:
    plt.barh(skill_gaps_data, range(1, len(skill_gaps_data) + 1), color=colors[7])
    plt.xlabel('Priority Level')
    plt.title('Top Skill Gaps to Address')
    plt.gca().invert_yaxis()
plt.show()

# Plot 9: Learning Path Timeline
plt.figure(figsize=(10, 6))
if learning_path_data:
    steps = [f"Step {step['step']}" for step in learning_path_data]
    durations = [step['duration_weeks'] for step in learning_path_data]
    plt.bar(steps, durations, color=colors[8])
    plt.ylabel('Weeks')
    plt.title('Learning Path Timeline')
plt.show()

# Plot 10: Career Progression Path
plt.figure(figsize=(10, 6))
if career_progression_data:
    steps = [f"Step {p['step']}" for p in career_progression_data]
    plt.plot(steps, range(len(steps)), marker='o', color=colors[9])
    plt.ylabel('Progression Level')
    plt.title('Career Progression Path')
    plt.xticks(rotation=45)
plt.show()

# Plot 11: Job Type Distribution
plt.figure(figsize=(8, 8))
plt.pie(job_types_data.values(), labels=job_types_data.keys(), autopct='%1.1f%%')
plt.title('Job Type Distribution')
plt.show()